<script lang="ts">
    import { selectedWorld } from "/src/utilities/worldConfig";
    import { breadcrumb } from "/src/utilities/breadCrumbStore";
    import Breadcrumb from "/src/ui/components/Breadcrumb/Breadcrumb.svelte";

    import { onMount } from "svelte";
    import ListSelector from "/src/ui/components/ListSelector/ListSelector.svelte";
    import BigButton from "/src/ui/components/BigButton/BigButton.svelte";
    import VerticleList from "/src/ui/components/VerticleList/VerticleList.svelte";
    import ModWindow from "/src/ui/components/ModWindow/ModWindow.svelte";
    import { user } from "/src/stores";
    import { DeleteRaceFromWorld } from "/src/utilities/charManager";
    import type { Race } from "/src/utilities/charManager";
    // import { DeleteRaceFromWorld } from "/src/utilities/charManager";

    onMount(async () => {
        if ($selectedWorld) {
            //do stuff
            $breadcrumb.current = "Races";
            $breadcrumb.currentType = "world";
            $breadcrumb.path = [
                {
                    url: `/dm/dashboard/${$selectedWorld.name}`,
                    name: $selectedWorld.name,
                },
            ];
        }
    });

    let selectedRace: undefined | Race = undefined;
    let toggleMod;
</script>

<ModWindow bind:this={toggleMod} />

<ListSelector items={$selectedWorld.races} bind:selectedItem={selectedRace} />

<VerticleList>
    {#if selectedRace}
        <BigButton
            type="good"
            func={() => toggleMod.toggleMod()}
            nav={`/dm/dashboard/${$selectedWorld.name}/races/${selectedRace.name}`}
            >Select Race</BigButton
        >
        <BigButton
            type="warning"
            func={() => {
                $selectedWorld = DeleteRaceFromWorld($user, selectedRace);
                selectedRace = undefined;
            }}>Delete Race</BigButton
        >
    {/if}
    <BigButton nav={`/dm/dashboard/${$selectedWorld.name}/races/New Race`}
        >Create Race</BigButton
    >
</VerticleList>

<!-- 

    DM PROMPTS:

    in-short:
    a page that helps dms manage a session by giving them promts that they can create

    long explination
    : a new dm or perhaps a unorganized dm wants to run a game, so they create a campign.
    they create a session within the campaign that allows them to create a play-by-play of how
    they want to run the game.

    a session contains promps which could either be generated by the dm,players or randomly. These promps could be as
    simple as a plot point, or more specific like character dialog.

    DM-promt: 
    "You arrive in a small village. The streets are cobbled with very fine looking houses that line the street.
    as you walk down the street, the locals stare at you with a look of mild bitterness. A very well dressed man sitting
    outside a shop call Talon's Workshop stands up and moves to block your path. He says: 'Hey, you aren't from around here,
    what's yer busniess here?' "

    These promts would be avalible for a dm to see in a timeline


 -->
